# Generated by Django 3.0.8 on 2020-08-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200809_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='desciption',
            new_name='description',
        ),
    ]
