# Generated by Django 3.0.8 on 2020-08-10 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200809_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='desc',
        ),
    ]
