# Generated by Django 3.0.8 on 2020-08-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='auther',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
