# Generated by Django 3.0.8 on 2020-08-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thumbupcount',
            field=models.IntegerField(default=0),
        ),
    ]
