# Generated by Django 3.0.8 on 2020-08-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20200811_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacherid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
