# Generated by Django 3.0.8 on 2020-08-12 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_user_teacherid'),
    ]

    operations = [
        migrations.CreateModel(
            name='thumbuporcancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbuporcancel_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.paper')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
