# Generated by Django 3.0.8 on 2020-08-14 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_thumbuporcancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='submitdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', models.TextField(default='')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='workf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('currentstate', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_work', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionname', models.CharField(max_length=200)),
                ('creattime', models.DateTimeField(auto_now_add=True)),
                ('nextstate', models.CharField(max_length=100)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submitdata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.submitdata')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_step', to='common.workf')),
            ],
        ),
    ]
