# Generated by Django 3.0.8 on 2020-08-14 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_steps_submitdata_workf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='submitdata',
        ),
        migrations.AddField(
            model_name='submitdata',
            name='step',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='common.steps'),
        ),
    ]
