# Generated by Django 3.0.8 on 2020-08-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20200814_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steps',
            old_name='nextstate',
            new_name='state',
        ),
    ]
