# Generated by Django 3.0.8 on 2020-08-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20200815_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='workf',
            name='teacher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
